export const IPC_CHANNELS = {
  SYSTEM_INFO: 'system:info',
  MONITORING_START: 'monitoring:start',
  MONITORING_STOP: 'monitoring:stop',
  MONITORING_HEALTH: 'monitoring:health',
  TERMINAL_SPAWN: 'terminal:spawn',
  TERMINAL_WRITE: 'terminal:write',
  TERMINAL_RESIZE: 'terminal:resize',
  TERMINAL_KILL: 'terminal:kill',
  FILES_LARGE: 'files:large',
  FILES_DUPLICATES: 'files:duplicates',
  FILES_DELETE: 'files:delete',
  GIT_STATUS: 'git:status',
  GIT_BRANCHES: 'git:branches',
  GIT_COMMIT: 'git:commit',
  GIT_PULL: 'git:pull',
  GIT_PUSH: 'git:push',
  GIT_STASH: 'git:stash',
  GIT_CHECKOUT: 'git:checkout',
  DOCKER_CONTAINERS: 'docker:containers',
  DOCKER_IMAGES: 'docker:images',
  DOCKER_VOLUMES: 'docker:volumes',
  DOCKER_NETWORKS: 'docker:networks',
  DOCKER_ACTION: 'docker:action',
  PORT_LIST: 'port:list',
  PROCESSES_LIST: 'processes:list',
  PROCESSES_ACTION: 'processes:action',
  PORTS_LIST: 'ports:list',
  PORTS_KILL: 'ports:kill',
  PROJECTS_SCAN: 'projects:scan',
  PROJECTS_START: 'projects:start',
  PROJECTS_STOP: 'projects:stop',
  PROJECTS_ENV_READ: 'projects:env:read',
  PROJECTS_ENV_WRITE: 'projects:env:write',
  DB_CONNECT: 'db:connect',
  DB_DISCONNECT: 'db:disconnect',
  DB_QUERY: 'db:query',
  DB_TABLES: 'db:tables',
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
